1>C:\Users\warre\source\repos\ConvergedConnector\Program.cs(18,13,18,19): error CS0103: The name 'SeedDb' does not exist in the current context 1>C:\Users\warre\source\repos\ConvergedConnector\Program.cs(27,63,27,78): error CS0246: The type or namespace name 'ConvergedSeeder' could not be found (are you missing a using directive or an assembly reference?) 1>C:\Users\warre\source\repos\ConvergedConnector\Data\ConvergedSeeder.cs(16,46,16,54): warning CS0649: Field 'ConvergedSeeder._hosting' is never assigned to, and will always have its default value null